import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { cn } from "@/lib/utils";
import type { RoleUser } from "@/types";

import Header from "@/components/Header";
import HeaderConditionnel from "@/components/HeaderConditionnel";
import Footer from "@/components/Footer";
import FooterConditionnel from "@/components/FooterConditionnel";
import BoutonFlottantPublier from "@/components/BoutonFlottantPublier";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-heading" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Move Ci",
  description: "Generated by create next app",
};

// 1. `RootLayout` doit devenir `async` : `cookies()` renvoie une Promise
//    dans cette version de Next (même mécanique que dans api/proxy/[...path]/route.ts
//    et api/auth/callback/route.ts — `(await cookies()).get(...)`).
//    Exemple : export default async function RootLayout({ children }: LayoutProps<"/">) {


// 2. Lis `auth_token` ET `user_role` sur les cookies entrants.
//    `estConnecte` = présence du token (booléen : `!!token`).
//    `role` = la valeur du cookie `user_role`, castée en `RoleUser`, ou `null`
//    si absente (utilisateur non connecté — pas de rôle à donner).
//    Exemple :
//    const cookieStore = await cookies();
//    const estConnecte = Boolean(cookieStore.get("auth_token")?.value);
//    const role = (cookieStore.get("user_role")?.value ?? null) as RoleUser | null;

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const estConnecte = Boolean(cookieStore.get("auth_token")?.value)
  const role = (cookieStore.get("user_role")?.value ?? null) as RoleUser | null;
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, montserrat.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" richColors />
        <HeaderConditionnel>
          <Header estConnecte={estConnecte} role={role} />
        </HeaderConditionnel>
        {children}
        <BoutonFlottantPublier role={role} />
        <FooterConditionnel>
          <Footer />
        </FooterConditionnel>
      </body>
    </html>
  );
}
