/**
 * Catalogue marque → modèles pour le Combobox de PostVehiculeContent. Liste
 * commerciale statique (pas de table `marques`/`modeles` côté back) : le champ
 * `marque`/`modele` reste une simple string en base (VehiculesController::postVehicules,
 * `'marque' => 'required|string|max:500'`), ce fichier ne fait que peupler l'UI.
 */
export const MARQUES = [
  "Toyota",
  "Hyundai",
  "Kia",
  "Nissan",
  "Mercedes-Benz",
  "BMW",
  "Audi",
  "Volkswagen",
  "Peugeot",
  "Renault",
  "Citroën",
  "Ford",
  "Chevrolet",
  "Honda",
  "Mazda",
  "Mitsubishi",
  "Suzuki",
  "Isuzu",
  "Land Rover",
  "Jeep",
  "Dacia",
  "Fiat",
  "Opel",
  "Volvo",
  "Lexus",
  "Infiniti",
  "Subaru",
  "Chery",
  "Great Wall",
  "Haval",
  "MG",
  "BYD",
  "Geely",
  "JAC",
  "DFSK",
  "Foton",
  "Tata",
  "Mahindra",
  "Porsche",
  "Jaguar",
  "Mini",
  "Alfa Romeo",
  "Seat",
  "Škoda",
  "SsangYong",
  "GMC",
  "Cadillac",
  "Acura",
  "Bentley",
  "Autre",
] as const;

export type Marque = (typeof MARQUES)[number];

/** Pas exhaustif — les modèles les plus courants sur le marché ivoirien pour chaque marque. */
export const MODELES_PAR_MARQUE: Record<Marque, string[]> = {
  Toyota: ["Corolla", "Camry", "Yaris", "RAV4", "Land Cruiser", "Hilux", "Prado", "Avensis", "Auris", "C-HR", "Fortuner", "Highlander"],
  Hyundai: ["Accent", "Elantra", "Tucson", "Santa Fe", "i10", "i20", "i30", "Sonata", "Creta", "Kona"],
  Kia: ["Picanto", "Rio", "Cerato", "Sportage", "Sorento", "Seltos", "Soul", "Optima", "Carnival"],
  Nissan: ["Micra", "Sentra", "Altima", "Qashqai", "X-Trail", "Juke", "Patrol", "Navara", "Rogue", "Pathfinder"],
  "Mercedes-Benz": ["Classe A", "Classe C", "Classe E", "Classe S", "Classe G", "GLA", "GLC", "GLE", "GLS", "Vito"],
  BMW: ["Série 1", "Série 3", "Série 5", "Série 7", "X1", "X3", "X5", "X6", "Z4"],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "TT"],
  Volkswagen: ["Golf", "Polo", "Passat", "Tiguan", "Touareg", "Jetta", "Amarok", "T-Roc", "Caddy"],
  Peugeot: ["208", "301", "308", "3008", "5008", "406", "407", "508", "Partner"],
  Renault: ["Clio", "Megane", "Duster", "Logan", "Sandero", "Kadjar", "Koleos", "Symbol"],
  Citroën: ["C3", "C4", "C5", "Berlingo", "C-Elysée", "Jumpy"],
  Ford: ["Fiesta", "Focus", "Ranger", "Explorer", "EcoSport", "Escape", "Everest", "Edge"],
  Chevrolet: ["Aveo", "Cruze", "Spark", "Captiva", "Trailblazer", "Malibu"],
  Honda: ["Civic", "Accord", "CR-V", "HR-V", "Pilot", "Jazz"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "BT-50"],
  Mitsubishi: ["Lancer", "Outlander", "Pajero", "ASX", "L200", "Eclipse Cross"],
  Suzuki: ["Swift", "Vitara", "Jimny", "Baleno", "Celerio", "Ertiga"],
  Isuzu: ["D-Max", "MU-X", "Trooper"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Evoque", "Discovery", "Defender"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler"],
  Dacia: ["Sandero", "Duster", "Logan", "Lodgy"],
  Fiat: ["500", "Panda", "Tipo", "Doblo"],
  Opel: ["Corsa", "Astra", "Insignia", "Mokka"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90"],
  Lexus: ["IS", "ES", "RX", "NX", "LX", "GX"],
  Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
  Subaru: ["Impreza", "Forester", "Outback", "XV"],
  Chery: ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5"],
  "Great Wall": ["Wingle", "Poer", "Haval H6"],
  Haval: ["H6", "Jolion", "H9"],
  MG: ["MG3", "MG5", "ZS", "HS"],
  BYD: ["Song Plus", "Atto 3", "Han", "Tang"],
  Geely: ["Coolray", "Emgrand", "Azkarra"],
  JAC: ["J7", "T6", "S3"],
  DFSK: ["Glory 580", "K01", "K02"],
  Foton: ["Tunland", "View"],
  Tata: ["Nexon", "Xenon", "Ace"],
  Mahindra: ["Scorpio", "XUV500", "Bolero", "Thar"],
  Porsche: ["Cayenne", "Macan", "Panamera", "911"],
  Jaguar: ["XE", "XF", "F-Pace", "E-Pace"],
  Mini: ["Cooper", "Countryman", "Clubman"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Giulietta"],
  Seat: ["Ibiza", "Leon", "Ateca", "Arona"],
  Škoda: ["Fabia", "Octavia", "Superb", "Kodiaq"],
  SsangYong: ["Korando", "Rexton", "Tivoli", "Musso"],
  GMC: ["Sierra", "Yukon", "Terrain", "Acadia"],
  Cadillac: ["Escalade", "XT5", "CT5"],
  Acura: ["MDX", "RDX", "TLX"],
  Bentley: ["Continental GT", "Bentayga", "Flying Spur"],
  Autre: [],
};
